# Generated by Django 3.0.4 on 2020-03-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20200319_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="web_link",
            field=models.CharField(
                blank=True,
                help_text="Link to access payment page.",
                max_length=1000,
                null=True,
            ),
        ),
    ]
