# Generated by Django 3.0.4 on 2020-03-17 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the goal.', max_length=60, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this goal. Generated by the system.', max_length=60)),
                ('description', models.TextField(help_text='The full details of the goal.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this goal was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this goal was updated. Automatically generated when the model updates.')),
                ('achievements', models.IntegerField(help_text='The number of time periods you have met this goal. Honor system!')),
                ('fails', models.IntegerField(help_text='The number of time periods you have missed this goal. Honor system!')),
                ('author', models.ForeignKey(help_text='The user that posted this article.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Main gist of the comment.', max_length=60)),
                ('description', models.TextField(help_text='Full description of comment.')),
                ('last_modified', models.DateTimeField(auto_now_add=True, help_text='The date and time this comment was last edited. Auto-generated.')),
                ('goal', models.ForeignKey(help_text='Goal referred to by the comment.', on_delete=django.db.models.deletion.PROTECT, to='budget.Goal')),
                ('user', models.OneToOneField(help_text='User who wrote the comment.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
