# Generated by Django 3.0.4 on 2020-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200323_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mugshot',
            field=models.ImageField(blank=True, default='images/user-icon.jpg', help_text='User profile image', null=True, upload_to='images/'),
        ),
    ]
