from django.db import models
from django.conf import settings as dj_conf_settings
import conscious_consumer.settings as cc_settings


class Product(models.Model):
    title = models.CharField(max_length=cc_settings.LABEL_MAX_LENGTH,
                             unique=True,
                             help_text="What the product is called.")
    slug = models.CharField(max_length=cc_settings.LABEL_MAX_LENGTH,
                            blank=True, editable=False,
                            help_text=(
                                "Unique URL path to access this product. "
                                + "Generated by the system."))
    description = models.TextField(help_text=(
                                   "What customers should know." +
                                   "Please include the link, if you're selling"
                                   + " on a different website."))
    photo = models.ImageField(upload_to='images/', null=True, blank=True,
                              help_text="Image of the product, if possible.")
    price = models.FloatField(help_text="Cost of product (USD).")
    seller = models.OneToOneField(dj_conf_settings.AUTH_USER_MODEL,
                                  on_delete=models.PROTECT,
                                  help_text="User who posted this product.")


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT,
                                help_text="Product being reviewed.")
    headline = models.CharField(max_length=cc_settings.LABEL_MAX_LENGTH,
                                unique=False,
                                help_text="Main point of review.")
    description = models.TextField(help_text="Full thoughts on product.")
    author = models.OneToOneField(dj_conf_settings.AUTH_USER_MODEL,
                                  on_delete=models.PROTECT,
                                  help_text="User leaving the review.")
    rating = models.IntegerField(help_text=(
                                "1 to 5 stars, where 5 is highest rating."))
    modified = models.DateTimeField(auto_now=True,
                                    help_text=(
                                        "The date and time this product " +
                                        "was posted. Automatically " +
                                        "generated when the model updates."))
